language: ruby
rvm:
  - 2.5.0

before_install:
  - gem update --system
  - gem install bundler

script:
  - bundle install 
  # - jobs=3 
  # - retry=3
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  # — bundle exec rspec
