
language: ruby
rvm:
  - 2.6.3

before_install:
  - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  - brew install ImageMagick
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - yarn install --check-file
  - gem update --system
  - gem install bundler

services:
  - postgresql

script:
  - bundle install
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - bundle exec rspec
