development:
  adapter: postgresql

test:
  adapter: test

production:
  adapter: postgresql
  # url: redis://redistogo:06b1955c23c0529bf60311c797d688fd@hammerjaw.redistogo.com:11974/
  # channel_prefix: acebook_production
