development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:06b1955c23c0529bf60311c797d688fd@hammerjaw.redistogo.com:11974/
  channel_prefix: acebook_production
